apiVersion: v1
kind: Template
metadata:
  name: pipeline-resources-template
  annotations:
    description: 'Template to create project specific Pipeline resources.'
objects:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: transformer-repo
  spec:
    type: git
    params:
    - name: url
      value: https://github.com/puzzle/quarkus-techlab-data-transformer.git
    - name: revision
      value: master
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: transformer-image
  spec:
    type: image
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}/data-transformer:latest
parameters:
- description: OpenShift Project Name
  name: PROJECT_NAME
  mandatory: true