apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: data-producer
    application: amm-techlab
  name: data-producer
spec:
  output:
    to:
      kind: ImageStreamTag
      name: data-producer:rest
  postCommit: {}
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  source:
    git:
      uri: https://github.com/puzzle/quarkus-techlab-data-producer.git
      ref: rest
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.binary
    type: Docker
  triggers:
  - github:
      secret: PPMUkybOXqfoY_bJd-ou
    type: GitHub
  - generic:
      secret: f31PWzHXBGI9iYw-fTli
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
