apiVersion: v1
kind: Service
metadata:
  name: data-producer
  labels:
    application: amm-techlab
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: data-producer
  sessionAffinity: None
  type: ClusterIP
